<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageId>Void.Templates</PackageId>
    <Version>1.0.0</Version>
    <Description>Project templates for Void Engine games.</Description>
    <Authors>Shmellyorc</Authors>
    <Company>Void Engine</Company>
    <Copyright>Copyright (c) 2026 Void Engine</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageType>Template</PackageType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageTags>void;engine;template;game;dotnet;csharp;2d</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Shmellyorc/Void</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Shmellyorc/Void</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>

    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="templates\**\*" Exclude="templates\**\bin\**;templates\**\obj\**" />
    <Compile Remove="templates\**\*" />
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\Images\Icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>