using RenderPrimitiveType = Void.Engine.Graphics.Rendering.PrimitiveType;
using RenderVertex = Void.Engine.Graphics.Rendering.Vertex;

// ============================================================================
//  PrimitiveBatcher.cs
// ============================================================================
//  Batched drawing for renderer-neutral 2D primitive geometry.
//
//  Copyright (c) 2026 Void Engine
//  Licensed under the MIT License.
// ============================================================================

namespace Void.Engine.Graphics;

/// <summary>
/// Batches points, lines, rectangles, circles, polygons, and triangles.
/// </summary>
/// <remarks>
/// <para>
/// Primitive geometry is written directly into the CPU-side vertex stream as draw
/// methods are called. Depth sorting, when enabled, reorders commands and rebuilds
/// the stream before upload. Contiguous point, independent-line, and independent-triangle
/// commands can share one draw submission. Strip and fan commands remain separate so
/// their topology cannot connect otherwise independent shapes.
/// </para>
/// <para>
/// Filled polygons are triangulated as a fan from the first vertex, so callers
/// should supply vertices in an order suitable for fan triangulation.
/// </para>
/// <para><code>
/// using var batcher = new PrimitiveBatcher();
/// batcher.Begin();
/// batcher.DrawRect(new Vect2(16, 16), new Vect2(64, 32), Color.White);
/// batcher.DrawLine(new Vect2(0, 0), new Vect2(80, 40), Color.Red);
/// batcher.End();
/// </code></para>
/// </remarks>
public sealed class PrimitiveBatcher : BaseBatcher
{
    private const int MaxCircleSegments = 256;
    private const int MinCircleSegments = 3;
    private const int DefaultCircleSegments = 32;

    private struct PrimitiveCommand
    {
        public RenderPrimitiveType PrimitiveType;
        public int VertexCount;
        public int VertexOffset;
        public float Depth;
    }

    private PrimitiveCommand[] _cmds;
    private readonly PrimitiveCommandComparer _comparer;
    private int _vertexIndex;
    private RenderVertex[] _sortedVertexData;

    /// <summary>Gets the diagnostic name of this batcher.</summary>
    public override string Name => "PrimitiveBatcher";

    /// <summary>Gets the base allocation multiplier used by <see cref="BaseBatcher"/>.</summary>
    protected override int VerticesPerCommand => 1;

    /// <summary>Initializes a primitive batcher.</summary>
    /// <param name="capacity">Initial command capacity, or zero to use the configured default.</param>
    public PrimitiveBatcher(int capacity = 0) : base(capacity)
    {
        _cmds = new PrimitiveCommand[_capacity];
        _sortedVertexData = new RenderVertex[_vertexBufferSize];
        _comparer = new PrimitiveCommandComparer(_sortMode);
        _vertexIndex = 0;
    }

    /// <summary>Gets the configured default primitive command capacity.</summary>
    /// <returns><see cref="GameSettings.PrimitiveBatchCapacity"/>.</returns>
    protected override int GetDefaultCapacity() => GameSettings.Instance.PrimitiveBatchCapacity;

    /// <summary>Resets the primitive vertex cursor when a batch begins.</summary>
    protected override void OnBegin() => _vertexIndex = 0;

    /// <summary>Handles the end-of-batch hook.</summary>
    protected override void OnEnd() { }

    /// <summary>Resets the primitive vertex cursor after a flush.</summary>
    protected override void OnFlush() => _vertexIndex = 0;

    /// <summary>Sorts commands and rebuilds their vertex ranges in sorted order.</summary>
    protected override void SortCommands()
    {
        _comparer.UpdateMode(_sortMode);
        Array.Sort(_cmds, 0, _cmdCount, _comparer);
        RebuildSortedVertices();
    }

    private void RebuildSortedVertices()
    {
        if (_sortedVertexData.Length < _vertexIndex)
            Array.Resize(ref _sortedVertexData, _vertexIndex);

        int sortedIndex = 0;

        for (int i = 0; i < _cmdCount; i++)
        {
            PrimitiveCommand cmd = _cmds[i];

            _vertexData
                .AsSpan(cmd.VertexOffset, cmd.VertexCount)
                .CopyTo(_sortedVertexData.AsSpan(sortedIndex, cmd.VertexCount));

            _cmds[i].VertexOffset = sortedIndex;
            sortedIndex += cmd.VertexCount;
        }
    }

    /// <summary>
    /// Performs no additional vertex build because primitive vertices are generated by draw calls.
    /// </summary>
    protected override void BuildVertices() { }

    /// <summary>Submits the currently queued primitive commands.</summary>
    /// <remarks>
    /// Statistics are replaced with values for this flush. Triangle counts are
    /// derived from each queued command's primitive topology.
    /// </remarks>
    public override void Flush()
    {
        if (_cmdCount == 0) return;

        long startTimestamp = System.Diagnostics.Stopwatch.GetTimestamp();

        bool requiresSorting = _sortMode != SortMode.Immediate && _sortMode != SortMode.Deferred;
        ReadOnlySpan<RenderVertex> uploadVertices = _vertexData;

        if (requiresSorting)
        {
            SortCommands();
            uploadVertices = _sortedVertexData;
        }

        _vertexBuffer.Update(uploadVertices, (uint)_vertexIndex, 0);

        _renderStates.Texture = null;
        _renderStates.Shader = _currentShader;

        int drawCalls = 0;
        int triangleCount = 0;
        int index = 0;
        while (index < _cmdCount)
        {
            PrimitiveCommand firstCommand = _cmds[index];
            RenderPrimitiveType currentType = firstCommand.PrimitiveType;
            int vertexStart = firstCommand.VertexOffset;
            int vertexCount = firstCommand.VertexCount;
            triangleCount += CountTriangles(currentType, firstCommand.VertexCount);
            index++;

            if (CanMergePrimitiveCommands(currentType))
            {
                while (index < _cmdCount && _cmds[index].PrimitiveType == currentType)
                {
                    PrimitiveCommand command = _cmds[index];
                    vertexCount += command.VertexCount;
                    triangleCount += CountTriangles(command.PrimitiveType, command.VertexCount);
                    index++;
                }
            }

            _vertexBuffer.PrimitiveType = currentType;
            _vertexBuffer.Draw(_renderTarget, (uint)vertexStart, (uint)vertexCount, _renderStates);
            drawCalls++;
        }
        _stats.CPUTime = (float)System.Diagnostics.Stopwatch.GetElapsedTime(startTimestamp).TotalMilliseconds;
        _stats.DrawCalls = drawCalls;
        _stats.Vertices = _vertexIndex;
        _stats.Triangles = triangleCount;
        _stats.Commands = _cmdCount;

        _cmdCount = 0;
        _vertexIndex = 0;

        OnFlush();
    }

    /// <summary>Expands primitive command and vertex storage.</summary>
    protected override void ResizeBuffers()
    {
        Logger.Instance.DebugWithCategory("PrimitiveBatcher",
            "Resizing buffers: {0} -> {1} commands", _vertexBufferSize, _vertexBufferSize * 2);

        int newSize = _vertexBufferSize * 2;
        Array.Resize(ref _vertexData, newSize);
        Array.Resize(ref _sortedVertexData, newSize);
        _vertexBufferSize = newSize;

        _vertexBuffer?.Dispose();
        _vertexBuffer = new VertexBuffer(newSize);

        int newCmdSize = _cmds.Length * 2;
        Array.Resize(ref _cmds, newCmdSize);
        _capacity = newCmdSize;
    }

    /// <summary>Applies render state for a primitive command group.</summary>
    /// <param name="commandIndex">Index of the first command in the group.</param>
    protected override void SetRenderStateForGroup(int commandIndex)
    {
        base.SetRenderStateForGroup(commandIndex);
        ApplyShader();
    }

    private static bool CanMergePrimitiveCommands(RenderPrimitiveType primitiveType)
        => primitiveType is
            RenderPrimitiveType.Points or
            RenderPrimitiveType.Lines or
            RenderPrimitiveType.Triangles;

    private static int CountTriangles(RenderPrimitiveType primitiveType, int vertexCount)
        => primitiveType switch
        {
            RenderPrimitiveType.Triangles => vertexCount / 3,
            RenderPrimitiveType.TriangleStrip or RenderPrimitiveType.TriangleFan => Math.Max(0, vertexCount - 2),
            _ => 0
        };

    private void EnsureVertexCapacity(int needed)
    {
        while (_vertexIndex + needed > _vertexBufferSize)
            ResizeBuffers();
    }

    private void AddCommand(RenderPrimitiveType primitiveType, int vertexCount, float depth)
    {
        if (_cmdCount >= _cmds.Length)
        {
            int newCmdSize = _cmds.Length * 2;
            Array.Resize(ref _cmds, newCmdSize);
            _capacity = newCmdSize;
        }

        _cmds[_cmdCount] = new PrimitiveCommand
        {
            PrimitiveType = primitiveType,
            VertexCount = vertexCount,
            VertexOffset = _vertexIndex - vertexCount,
            Depth = depth
        };
        _cmdCount++;
    }

    #region Draw Methods

    /// <summary>Draws a line between two points.</summary>
    /// <param name="start">Line start.</param>
    /// <param name="end">Line end.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    /// <exception cref="ObjectDisposedException">Thrown when the batcher has been disposed.</exception>
    /// <exception cref="InvalidOperationException">Thrown when no batch is active.</exception>
    public void DrawLine(Vect2 start, Vect2 end, Color color, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");

        EnsureVertexCapacity(2);

        _vertexData[_vertexIndex++] = new RenderVertex(start, color);
        _vertexData[_vertexIndex++] = new RenderVertex(end, color);

        AddCommand(RenderPrimitiveType.Lines, 2, depth);
    }

    /// <summary>Draws one connected line strip through the supplied points.</summary>
    /// <param name="points">Points in strip order.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    /// <exception cref="ObjectDisposedException">Thrown when the batcher has been disposed.</exception>
    /// <exception cref="InvalidOperationException">Thrown when no batch is active.</exception>
    public void DrawLineStrip(ReadOnlySpan<Vect2> points, Color color, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");
        if (points.Length < 2) return;

        EnsureVertexCapacity(points.Length);

        for (int i = 0; i < points.Length; i++)
            _vertexData[_vertexIndex++] = new RenderVertex(points[i], color);

        AddCommand(RenderPrimitiveType.LineStrip, points.Length, depth);
    }

    /// <summary>Draws a single point primitive.</summary>
    /// <param name="position">Point position.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    /// <exception cref="ObjectDisposedException">Thrown when the batcher has been disposed.</exception>
    /// <exception cref="InvalidOperationException">Thrown when no batch is active.</exception>
    public void DrawPoint(Vect2 position, Color color, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");

        EnsureVertexCapacity(1);

        _vertexData[_vertexIndex++] = new RenderVertex(position, color);

        AddCommand(RenderPrimitiveType.Points, 1, depth);
    }

    /// <summary>Draws the supplied positions as point primitives.</summary>
    /// <param name="positions">Point positions.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    /// <remarks>An empty span is ignored.</remarks>
    /// <exception cref="ObjectDisposedException">Thrown when the batcher has been disposed.</exception>
    /// <exception cref="InvalidOperationException">Thrown when no batch is active.</exception>
    public void DrawPoints(ReadOnlySpan<Vect2> positions, Color color, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");
        if (positions.IsEmpty) return;

        EnsureVertexCapacity(positions.Length);

        for (int i = 0; i < positions.Length; i++)
            _vertexData[_vertexIndex++] = new RenderVertex(positions[i], color);

        AddCommand(RenderPrimitiveType.Points, positions.Length, depth);
    }

    /// <summary>Draws a filled axis-aligned rectangle.</summary>
    /// <param name="position">Rectangle position.</param>
    /// <param name="size">Rectangle size.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawRect(Vect2 position, Vect2 size, Color color, float depth = 0f)
    {
        DrawRect(position, size, color, Vect2.One, 0f, Vect2.Zero, depth);
    }

    /// <summary>Draws a filled rectangle with scale, rotation, and origin.</summary>
    /// <param name="position">Rectangle position.</param>
    /// <param name="size">Unscaled rectangle size.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="scale">Scale applied to local rectangle coordinates.</param>
    /// <param name="rotation">Rotation in radians.</param>
    /// <param name="origin">Origin used for the transformation.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawRect(Vect2 position, Vect2 size, Color color, Vect2 scale, float rotation, Vect2 origin, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");

        EnsureVertexCapacity(6);

        Vect2 p0 = new(0, 0);
        Vect2 p1 = new(size.X, 0);
        Vect2 p2 = new(size.X, size.Y);
        Vect2 p3 = new(0, size.Y);

        if (rotation != 0f || scale != Vect2.One || origin != Vect2.Zero)
        {
            float cos = MathF.Cos(rotation);
            float sin = MathF.Sin(rotation);
            float ox = origin.X * scale.X;
            float oy = origin.Y * scale.Y;

            Vect2 Transform(Vect2 p)
            {
                float sx = p.X * scale.X - ox;
                float sy = p.Y * scale.Y - oy;
                return new Vect2(
                    position.X + sx * cos - sy * sin + ox,
                    position.Y + sx * sin + sy * cos + oy
                );
            }

            p0 = Transform(p0);
            p1 = Transform(p1);
            p2 = Transform(p2);
            p3 = Transform(p3);
        }
        else
        {
            p0 += position;
            p1 += position;
            p2 += position;
            p3 += position;
        }

        _vertexData[_vertexIndex++] = new RenderVertex(p0, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p1, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p2, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p0, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p2, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p3, color);

        AddCommand(RenderPrimitiveType.Triangles, 6, depth);
    }

    /// <summary>Draws an axis-aligned rectangle outline.</summary>
    /// <param name="position">Rectangle position.</param>
    /// <param name="size">Rectangle size.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawRectOutline(Vect2 position, Vect2 size, Color color, float depth = 0f)
        => DrawRectOutline(position, size, color, Vect2.One, 0f, Vect2.Zero, depth);

    /// <summary>Draws a rectangle outline with scale, rotation, and origin.</summary>
    /// <param name="position">Rectangle position.</param>
    /// <param name="size">Unscaled rectangle size.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="scale">Scale applied to local rectangle coordinates.</param>
    /// <param name="rotation">Rotation in radians.</param>
    /// <param name="origin">Origin used for the transformation.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawRectOutline(Vect2 position, Vect2 size, Color color, Vect2 scale, float rotation, Vect2 origin, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");

        EnsureVertexCapacity(8);

        Vect2 p0 = new(0, 0);
        Vect2 p1 = new(size.X, 0);
        Vect2 p2 = new(size.X, size.Y);
        Vect2 p3 = new(0, size.Y);

        if (rotation != 0f || scale != Vect2.One || origin != Vect2.Zero)
        {
            float cos = MathF.Cos(rotation);
            float sin = MathF.Sin(rotation);
            float ox = origin.X * scale.X;
            float oy = origin.Y * scale.Y;

            Vect2 Transform(Vect2 p)
            {
                float sx = p.X * scale.X - ox;
                float sy = p.Y * scale.Y - oy;
                return new Vect2(
                    position.X + sx * cos - sy * sin + ox,
                    position.Y + sx * sin + sy * cos + oy
                );
            }

            p0 = Transform(p0);
            p1 = Transform(p1);
            p2 = Transform(p2);
            p3 = Transform(p3);
        }
        else
        {
            p0 += position;
            p1 += position;
            p2 += position;
            p3 += position;
        }

        _vertexData[_vertexIndex++] = new RenderVertex(p0, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p1, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p1, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p2, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p2, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p3, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p3, color);
        _vertexData[_vertexIndex++] = new RenderVertex(p0, color);

        AddCommand(RenderPrimitiveType.Lines, 8, depth);
    }

    /// <summary>Draws a filled circle using the default segment count.</summary>
    /// <param name="center">Circle center.</param>
    /// <param name="radius">Circle radius.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawCircle(Vect2 center, float radius, Color color, float depth = 0f)
        => DrawCircle(center, radius, DefaultCircleSegments, color, Vect2.One, 0f, Vect2.Zero, depth);

    /// <summary>Draws a filled circle using an explicit segment count.</summary>
    /// <param name="center">Circle center.</param>
    /// <param name="radius">Circle radius.</param>
    /// <param name="segments">Requested segment count, clamped from 3 through 256.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawCircle(Vect2 center, float radius, int segments, Color color, float depth = 0f)
        => DrawCircle(center, radius, segments, color, Vect2.One, 0f, Vect2.Zero, depth);

    /// <summary>Draws a filled circle with scale, rotation, and origin.</summary>
    /// <param name="center">Circle center.</param>
    /// <param name="radius">Circle radius.</param>
    /// <param name="segments">Requested segment count, clamped from 3 through 256.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="scale">Scale applied to generated circle coordinates.</param>
    /// <param name="rotation">Rotation in radians.</param>
    /// <param name="origin">Origin used for the transformation.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawCircle(Vect2 center, float radius, int segments, Color color, Vect2 scale, float rotation, Vect2 origin, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");

        segments = Math.Clamp(segments, MinCircleSegments, MaxCircleSegments);

        int vertexCount = segments + 2;
        EnsureVertexCapacity(vertexCount);

        float cos = MathF.Cos(rotation);
        float sin = MathF.Sin(rotation);

        _vertexData[_vertexIndex++] = new RenderVertex(center, color);

        for (int i = 0; i <= segments; i++)
        {
            float angle = (float)i / segments * MathF.PI * 2f;
            float x = MathF.Cos(angle) * radius;
            float y = MathF.Sin(angle) * radius;

            float sx = x * scale.X - origin.X;
            float sy = y * scale.Y - origin.Y;
            float rx = sx * cos - sy * sin + origin.X;
            float ry = sx * sin + sy * cos + origin.Y;

            _vertexData[_vertexIndex++] = new RenderVertex(
                new Vect2(center.X + rx, center.Y + ry),
                color
            );
        }

        AddCommand(RenderPrimitiveType.TriangleFan, vertexCount, depth);
    }

    /// <summary>Draws a circle outline using the default segment count.</summary>
    /// <param name="center">Circle center.</param>
    /// <param name="radius">Circle radius.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawCircleOutline(Vect2 center, float radius, Color color, float depth = 0f)
        => DrawCircleOutline(center, radius, DefaultCircleSegments, color, Vect2.One, 0f, Vect2.Zero, depth);

    /// <summary>Draws a circle outline using an explicit segment count.</summary>
    /// <param name="center">Circle center.</param>
    /// <param name="radius">Circle radius.</param>
    /// <param name="segments">Requested segment count, clamped from 3 through 256.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawCircleOutline(Vect2 center, float radius, int segments, Color color, float depth = 0f)
        => DrawCircleOutline(center, radius, segments, color, Vect2.One, 0f, Vect2.Zero, depth);

    /// <summary>Draws a circle outline with scale, rotation, and origin.</summary>
    /// <param name="center">Circle center.</param>
    /// <param name="radius">Circle radius.</param>
    /// <param name="segments">Requested segment count, clamped from 3 through 256.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="scale">Scale applied to generated circle coordinates.</param>
    /// <param name="rotation">Rotation in radians.</param>
    /// <param name="origin">Origin used for the transformation.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawCircleOutline(Vect2 center, float radius, int segments, Color color, Vect2 scale, float rotation, Vect2 origin, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");

        segments = Math.Clamp(segments, MinCircleSegments, MaxCircleSegments);

        int vertexCount = segments * 2;
        EnsureVertexCapacity(vertexCount);

        float cos = MathF.Cos(rotation);
        float sin = MathF.Sin(rotation);

        Vect2 firstPoint = default;
        Vect2 prevPoint = default;

        for (int i = 0; i < segments; i++)
        {
            float angle = (float)i / segments * MathF.PI * 2f;
            float x = MathF.Cos(angle) * radius;
            float y = MathF.Sin(angle) * radius;

            float sx = x * scale.X - origin.X;
            float sy = y * scale.Y - origin.Y;
            float rx = sx * cos - sy * sin + origin.X;
            float ry = sx * sin + sy * cos + origin.Y;

            var point = new Vect2(center.X + rx, center.Y + ry);

            if (i == 0)
            {
                firstPoint = point;
            }
            else
            {
                _vertexData[_vertexIndex++] = new RenderVertex(prevPoint, color);
                _vertexData[_vertexIndex++] = new RenderVertex(point, color);
            }

            prevPoint = point;
        }

        _vertexData[_vertexIndex++] = new RenderVertex(prevPoint, color);
        _vertexData[_vertexIndex++] = new RenderVertex(firstPoint, color);

        AddCommand(RenderPrimitiveType.Lines, vertexCount, depth);
    }

    /// <summary>Draws a filled polygon using fan triangulation.</summary>
    /// <param name="vertices">Polygon vertices in drawing order.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawPolygon(ReadOnlySpan<Vect2> vertices, Color color, float depth = 0f)
        => DrawPolygon(vertices, Vect2.Zero, color, Vect2.One, 0f, Vect2.Zero, depth);

    /// <summary>Draws a transformed filled polygon using fan triangulation.</summary>
    /// <param name="vertices">Polygon vertices in drawing order.</param>
    /// <param name="position">Position offset.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="scale">Scale applied to polygon coordinates.</param>
    /// <param name="rotation">Rotation in radians.</param>
    /// <param name="origin">Origin used for the transformation.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawPolygon(ReadOnlySpan<Vect2> vertices, Vect2 position, Color color, Vect2 scale, float rotation, Vect2 origin, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");
        if (vertices.Length < 3) return;

        int vertexCount = (vertices.Length - 2) * 3;
        EnsureVertexCapacity(vertexCount);

        float cos = MathF.Cos(rotation);
        float sin = MathF.Sin(rotation);

        Vect2 Transform(Vect2 p)
        {
            float sx = p.X * scale.X - origin.X;
            float sy = p.Y * scale.Y - origin.Y;
            return new Vect2(
                position.X + sx * cos - sy * sin + origin.X,
                position.Y + sx * sin + sy * cos + origin.Y
            );
        }

        Vect2 v0 = Transform(vertices[0]);

        for (int i = 1; i < vertices.Length - 1; i++)
        {
            Vect2 v1 = Transform(vertices[i]);
            Vect2 v2 = Transform(vertices[i + 1]);

            _vertexData[_vertexIndex++] = new RenderVertex(v0, color);
            _vertexData[_vertexIndex++] = new RenderVertex(v1, color);
            _vertexData[_vertexIndex++] = new RenderVertex(v2, color);
        }

        AddCommand(RenderPrimitiveType.Triangles, vertexCount, depth);
    }

    /// <summary>Draws a closed polygon outline.</summary>
    /// <param name="vertices">Polygon vertices in drawing order.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawPolygonOutline(ReadOnlySpan<Vect2> vertices, Color color, float depth = 0f)
        => DrawPolygonOutline(vertices, Vect2.Zero, color, Vect2.One, 0f, Vect2.Zero, depth);

    /// <summary>Draws a transformed closed polygon outline.</summary>
    /// <param name="vertices">Polygon vertices in drawing order.</param>
    /// <param name="position">Position offset.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="scale">Scale applied to polygon coordinates.</param>
    /// <param name="rotation">Rotation in radians.</param>
    /// <param name="origin">Origin used for the transformation.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawPolygonOutline(ReadOnlySpan<Vect2> vertices, Vect2 position, Color color, Vect2 scale, float rotation, Vect2 origin, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");
        if (vertices.Length < 2) return;

        int vertexCount = vertices.Length * 2;
        EnsureVertexCapacity(vertexCount);

        float cos = MathF.Cos(rotation);
        float sin = MathF.Sin(rotation);

        Vect2 Transform(Vect2 p)
        {
            float sx = p.X * scale.X - origin.X;
            float sy = p.Y * scale.Y - origin.Y;
            return new Vect2(
                position.X + sx * cos - sy * sin + origin.X,
                position.Y + sx * sin + sy * cos + origin.Y
            );
        }

        Vect2 first = Transform(vertices[0]);
        Vect2 prev = first;

        for (int i = 1; i < vertices.Length; i++)
        {
            Vect2 curr = Transform(vertices[i]);
            _vertexData[_vertexIndex++] = new RenderVertex(prev, color);
            _vertexData[_vertexIndex++] = new RenderVertex(curr, color);
            prev = curr;
        }

        _vertexData[_vertexIndex++] = new RenderVertex(prev, color);
        _vertexData[_vertexIndex++] = new RenderVertex(first, color);

        AddCommand(RenderPrimitiveType.Lines, vertexCount, depth);
    }

    /// <summary>Draws one filled triangle.</summary>
    /// <param name="a">First vertex.</param>
    /// <param name="b">Second vertex.</param>
    /// <param name="c">Third vertex.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawTriangle(Vect2 a, Vect2 b, Vect2 c, Color color, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");

        EnsureVertexCapacity(3);

        _vertexData[_vertexIndex++] = new RenderVertex(a, color);
        _vertexData[_vertexIndex++] = new RenderVertex(b, color);
        _vertexData[_vertexIndex++] = new RenderVertex(c, color);

        AddCommand(RenderPrimitiveType.Triangles, 3, depth);
    }

    /// <summary>Draws the three edges of a triangle.</summary>
    /// <param name="a">First vertex.</param>
    /// <param name="b">Second vertex.</param>
    /// <param name="c">Third vertex.</param>
    /// <param name="color">Vertex color.</param>
    /// <param name="depth">Depth value used by sorted modes.</param>
    public void DrawTriangleOutline(Vect2 a, Vect2 b, Vect2 c, Color color, float depth = 0f)
    {
        if (_isDisposed) throw new ObjectDisposedException(Name);
        if (!_isDrawing) throw new InvalidOperationException("Cannot draw outside Begin/End");

        EnsureVertexCapacity(6);

        _vertexData[_vertexIndex++] = new RenderVertex(a, color);
        _vertexData[_vertexIndex++] = new RenderVertex(b, color);
        _vertexData[_vertexIndex++] = new RenderVertex(b, color);
        _vertexData[_vertexIndex++] = new RenderVertex(c, color);
        _vertexData[_vertexIndex++] = new RenderVertex(c, color);
        _vertexData[_vertexIndex++] = new RenderVertex(a, color);

        AddCommand(RenderPrimitiveType.Lines, 6, depth);
    }

    #endregion

    private sealed class PrimitiveCommandComparer : IComparer<PrimitiveCommand>
    {
        private SortMode _sortMode;

        public PrimitiveCommandComparer(SortMode sortMode)
        {
            _sortMode = sortMode;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Compare(PrimitiveCommand a, PrimitiveCommand b)
        {
            if (_sortMode == SortMode.BackToFront)
            {
                if (a.Depth < b.Depth) return -1;
                if (a.Depth > b.Depth) return 1;
            }
            else if (_sortMode == SortMode.FrontToBack)
            {
                if (b.Depth < a.Depth) return -1;
                if (b.Depth > a.Depth) return 1;
            }

            if (a.PrimitiveType < b.PrimitiveType) return -1;
            if (a.PrimitiveType > b.PrimitiveType) return 1;

            return 0;
        }

        public void UpdateMode(SortMode sortMode) => _sortMode = sortMode;
    }
}
