global using System.Buffers;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO.Compression;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Serialization;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;

global using Void.Engine.Assets;
global using Void.Engine.Assets.Loaders;
global using Void.Engine.Assets.Loaders.Fonts;
global using Void.Engine.Assets.Loaders.LDtk;
global using Void.Engine.Assets.Loaders.LDtk.Instances;
global using Void.Engine.Assets.Loaders.Spritesheets;
global using Void.Engine.Assets.Mounts;
global using Void.Engine.Beacons;
global using Void.Engine.Coroutines;
global using Void.Engine.Graphics;
global using Void.Engine.Graphics.Atlas;
global using Void.Engine.Graphics.Atlas.Packers;
global using Void.Engine.Helpers;
global using Void.Engine.Inputs;
global using Void.Engine.Resources;
global using Void.Engine.Sounds;
global using Void.Engine.Sounds.EventArg;
global using Void.Engine.Systems;

global using SFBlendMode = SFML.Graphics.BlendMode;
global using SFClock = SFML.System.Clock;
global using SFColor = SFML.Graphics.Color;
global using SFContextSettings = SFML.Window.ContextSettings;
global using SFFloatRect = SFML.Graphics.FloatRect;
global using SFImage = SFML.Graphics.Image;
global using SFIntRect = SFML.Graphics.IntRect;
global using SFJoystick = SFML.Window.Joystick;
global using SFKeyboard = SFML.Window.Keyboard;
global using SFMouse = SFML.Window.Mouse;
global using SFMouseWheelScrollEventArgs = SFML.Window.MouseWheelScrollEventArgs;
global using SFPrimitiveType = SFML.Graphics.PrimitiveType;
global using SFRenderStates = SFML.Graphics.RenderStates;
global using SFRenderTexture = SFML.Graphics.RenderTexture;
global using SFRenderWindow = SFML.Graphics.RenderWindow;
global using SFSizeEventArgs = SFML.Window.SizeEventArgs;
global using SFSound = SFML.Audio.Sound;
global using SFSoundBuffer = SFML.Audio.SoundBuffer;
global using SFSprite = SFML.Graphics.Sprite;
global using SFStyles = SFML.Window.Styles;
global using SFTexture = SFML.Graphics.Texture;
global using SFTime = SFML.System.Time;
global using SFTransform = SFML.Graphics.Transform;
global using SFUsageSpecifier = SFML.Graphics.VertexBuffer.UsageSpecifier;
global using SFVector2f = SFML.System.Vector2f;
global using SFVector2i = SFML.System.Vector2i;
global using SFVector2u = SFML.System.Vector2u;
global using SFVertex = SFML.Graphics.Vertex;
global using SFVertexBuffer = SFML.Graphics.VertexBuffer;
global using SFVideoMode = SFML.Window.VideoMode;
global using SFView = SFML.Graphics.View;
